name: Documentaci칩n Autom치tica al Merge

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          
      - name: Generate Documentation from Code
        run: |
          echo "游닄 Generando documentaci칩n desde c칩digo fuente..."
          php generate-docs.php
      
      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: api-documentation
          path: docs-output/
          retention-days: 90